<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#第10章『多重比較法』" data-toc-modified-id="第10章『多重比較法』-1">第10章『多重比較法』</a></span><ul class="toc-item"><li><span><a href="#p.7" data-toc-modified-id="p.7-1.1">p.7</a></span></li><li><span><a href="#p.16~17" data-toc-modified-id="p.16~17-1.2">p.16~17</a></span></li></ul></li></ul></div>

# 第10章『多重比較法』

## p.7

In [2]:
import numpy as np
from statsmodels.stats.multitest import multipletests

### Pythonではどのように？おそらくメソッドがないのでは？
# https://github.com/statsmodels/statsmodels/wiki/SMEP:-Multi-Comparisons
### Tukey法のようなものはある
# http://lang.sist.chukyo-u.ac.jp/classes/PythonProbStat/Python-statistics6.html

# サンプルにこのデータを与える
data1 = np.array([59, 91, 64, 53, 75, 69, 36, 43, 54, 99])
data2 = np.array([67, 93, 72, 55, 109, 86, 50, 80, 95, 103])
multipletests(data1, data2)

/Users/yosukeitani/anaconda3/lib/python3.6/site-packages/statsmodels/stats/multitest.py:144: RuntimeWarning: invalid value encountered in power
  alphacSidak = 1 - np.power((1. - alphaf), 1./ntests)
/Users/yosukeitani/anaconda3/lib/python3.6/site-packages/statsmodels/stats/multitest.py:156: RuntimeWarning: invalid value encountered in power
  1./np.arange(ntests, 0, -1))
/Users/yosukeitani/anaconda3/lib/python3.6/site-packages/statsmodels/stats/multitest.py:157: RuntimeWarning: invalid value encountered in greater
  notreject = pvals > alphacSidak_all


(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 array([ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00, -2.75854735e+15,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00]),
 array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]),
 array([ 6.7,  9.3,  7.2,  5.5, 10.9,  8.6,  5. ,  8. ,  9.5, 10.3]))

## p.16~17

In [3]:
import numpy as np
import pandas as pd
import statsmodels.formula.api as sm

# https://www.statsmodels.org/dev/generated/statsmodels.regression.linear_model.OLSResults.get_prediction.html

time = [2, 4, 6, 8, 10]
y = [1.922, 1.443, 1.065, 0.703, 0.369]
data = pd.DataFrame({"time": time, "y": y})

result = sm.ols(formula='y ~ time', data=data)
result_fitted = result.fit()

prediction = result_fitted.get_prediction(pd.DataFrame({"time": [2]})) # timeの値が2の場合
prediction.summary_frame()

mean   mean_se  mean_ci_lower  mean_ci_upper  obs_ci_lower  obs_ci_upper
0  1.8696  0.038355       1.747537       1.991663      1.670271      2.068929